name: Build the shaweelAddons .jar file
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          
      - name: Fetch modVersion from gradle.properties
        run: |
          echo "MOD_VERSION=$(./gradlew properties -q | grep '^mod_version:' | awk '{print $2}')" >> $GITHUB_ENV
          
      - name: Build the shaweelAddons .jar file
        run: | 
          chmod +x ./gradlew
          ./gradlew build
          ls build/libs/
          mv build/libs/shaweeladdons-${{ env.MOD_VERSION }}.jar build/libs/shaweeladdons-v${{ env.MOD_VERSION }}-build${{ github.run_number }}.jar

      - name: Upload the shaweelAddons .jar file
        uses: actions/upload-artifact@v7
        with:
          path: build/libs/shaweeladdons-v${{ env.MOD_VERSION }}-build${{ github.run_number }}.jar
          archive: false
